name: Flutter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0' # or another version that you prefer

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.7' # specify the Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Create configuration
      run: |
        echo "// config.dart" > lib/config.dart
        echo "const String superSecretData = '${{ secrets.SUPER_SECRET_DATA }}';" >> lib/config.dart

    - name: Build Flutter Web
      run: flutter build web --release

    - name: Test
      run: dir

    - name: Install gh-pages
      run: npm install -g gh-pages@6.0.0

    - name: Deploy to GitHub Pages
      run: node --trace-warnings $(which gh-pages) -d build/web